### ISSUE TITLE
MC_pileip_f1 и Data_pileip_f1

### ISSUE THREAD

**Issue by BKirill** [jini-zh/tau-polarization#1]
https://github.com/jini-zh/tau-polarization/blob/598436bc821027087f4a629383f2fe06484c2102/src/Tau/TreeMakerMiniAOD/plugins/TTbarTauLepton.cc#L953-L956

Что именно происходит в этом цикле? Переменные `MC_pileip_f1` и `Data_pileip_f1` больше нигде в коде не встречаются - они импортируются откуда-то?

**Comment by Sirnobaka** [comment]
Здесь я пытался использовать для перевзвешивания встроенные в CMSSW инструменты, но результат был не очень хороший, поэтому я удалил кусок кода, а этот цикл, видимо, забыл.
Да, Data_pileip_f1 и MC_pileip_f1 импортируются, но можно спокойно удалять эти строки. Думаю, PileUP можно будет перевзвесить уже после аналайзера по данным о числе вершин из деревьев.

**Comment by BKirill** [comment]
Понял, спасибо за ответ!
