### ISSUE TITLE
nTauC

### ISSUE THREAD

**Issue by BKirill** [jini-zh/tau-polarization#2]
https://github.com/jini-zh/tau-polarization/blob/598436bc821027087f4a629383f2fe06484c2102/src/Tau/TreeMakerMiniAOD/plugins/TTbarTauLepton.cc#L2235

Что такое `nTauC`? Почему он считается после большинства катов, но до https://github.com/jini-zh/tau-polarization/blob/598436bc821027087f4a629383f2fe06484c2102/src/Tau/TreeMakerMiniAOD/plugins/TTbarTauLepton.cc#L2240

**Comment by Sirnobaka** [comment]
Это тоже типа наследия от первой версии кода. В отборах я нигде не использую переменную nTauc, но теоретически она может быть полезна.
Какие критерии отбора должны пройти кандидаты (то есть куда в коде поместить `++nTauc`), зависит от того, зачем нужно считать тау-кандидаты. Если тебе не нужна эта переменная, то можно вообще удалить её из кода.

**Comment by Sirnobaka** [comment]
Забыл написать, `nTauC` - это число кандидатов из коллекции тау, которые прошли определённые отборы. Наверное, то, что её инкремент стоит до отбора по dZ это просто ошибка. Думаю, первоначальная идея была в том, чтобы считать число кандидатов, которые прошли все отборы и "конкурировали" за то, чтобы стать конечным тау

**Comment by BKirill** [comment]
Понятно, спасибо!
